"""Durable store for live UPI contributions.

SQLite is the default. PostgreSQL is used when DATABASE_URL / --database
starts with postgres, so a remote database can gather writes in real time.
"""

from __future__ import annotations

import json
import sqlite3
import threading
from dataclasses import dataclass
from datetime import datetime, timezone
from hashlib import sha256
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS contributions (
        address TEXT PRIMARY KEY,
        record_type TEXT NOT NULL,
        status TEXT NOT NULL,
        title TEXT NOT NULL,
        payload TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        kind TEXT NOT NULL,
        address TEXT NOT NULL,
        payload TEXT NOT NULL,
        created_at TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS events_created_at ON events (created_at)",
)


def utcnow() -> str:
    """Return an aware UTC timestamp."""
    return datetime.now(timezone.utc).isoformat()


def content_hash(payload: dict[str, Any]) -> str:
    """Return a stable SHA-256 of canonical JSON."""
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return sha256(encoded).hexdigest()


@dataclass
class Contribution:
    """One stored node or bridge."""

    address: str
    record_type: str
    status: str
    title: str
    payload: dict[str, Any]
    content_hash: str
    created_at: str


class ContributionStore:
    """Append-only contribution database."""

    def __init__(self, database: str = "sqlite:///upi.db"):
        self.database = database
        self.kind, self._sqlite_path = _parse_database(database)
        self._lock = threading.Lock()
        self._pg = None
        self._sqlite_conn: sqlite3.Connection | None = None
        if self.kind == "postgres":
            self._connect_postgres()
        else:
            self._sqlite_conn = sqlite3.connect(self._sqlite_path, check_same_thread=False)
            self._sqlite_conn.row_factory = sqlite3.Row
        self._init()

    def _connect_postgres(self) -> None:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError(
                "PostgreSQL support requires: pip install 'universal-physics-index[postgres]'"
            ) from exc
        self._pg = psycopg.connect(self.database, autocommit=True, row_factory=dict_row)

    def _init(self) -> None:
        with self._lock:
            for statement in SCHEMA_STATEMENTS:
                sql = statement
                if self.kind == "postgres":
                    sql = sql.replace(
                        "INTEGER PRIMARY KEY AUTOINCREMENT",
                        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                    )
                    assert self._pg is not None
                    self._pg.execute(self._pg_sql(sql))
                else:
                    assert self._sqlite_conn is not None
                    self._sqlite_conn.execute(sql)
            if self._sqlite_conn is not None:
                self._sqlite_conn.commit()

    def get(self, address: str) -> Contribution | None:
        row = self._fetchone(
            "SELECT address, record_type, status, title, payload, content_hash, created_at "
            "FROM contributions WHERE address = ?",
            (address,),
        )
        return _row_to_contribution(row) if row else None

    def list_all(self, limit: int = 200) -> list[Contribution]:
        rows = self._fetchall(
            "SELECT address, record_type, status, title, payload, content_hash, created_at "
            "FROM contributions ORDER BY created_at DESC LIMIT ?",
            (limit,),
        )
        return [_row_to_contribution(row) for row in rows]

    def insert(self, record_type: str, payload: dict[str, Any]) -> Contribution:
        address = str(payload.get("address") or f"{payload.get('source')}->{payload.get('target')}")
        title = str(payload.get("title") or payload.get("relation") or address)
        status = str(payload.get("status") or "HYP")
        created = utcnow()
        digest = content_hash(payload)
        body = json.dumps(payload, ensure_ascii=False)
        self._execute(
            "INSERT INTO contributions "
            "(address, record_type, status, title, payload, content_hash, created_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (address, record_type, status, title, body, digest, created),
        )
        event = {
            "kind": "contribution",
            "address": address,
            "title": title,
            "status": status,
            "record_type": record_type,
            "created_at": created,
        }
        self._execute(
            "INSERT INTO events (kind, address, payload, created_at) VALUES (?, ?, ?, ?)",
            ("contribution", address, json.dumps(event, ensure_ascii=False), created),
        )
        stored = self.get(address)
        if stored is None:
            raise RuntimeError("contribution insert failed")
        return stored

    def events_since(self, last_id: int = 0, limit: int = 50) -> list[dict[str, Any]]:
        rows = self._fetchall(
            "SELECT id, kind, address, payload, created_at FROM events "
            "WHERE id > ? ORDER BY id ASC LIMIT ?",
            (last_id, limit),
        )
        events = []
        for row in rows:
            payload = json.loads(row["payload"])
            payload["id"] = row["id"]
            events.append(payload)
        return events

    def update_payload(self, address: str, payload: dict[str, Any]) -> Contribution:
        """Replace the stored payload for *address*."""
        title = str(payload.get("title") or payload.get("relation") or address)
        status = str(payload.get("status") or "HYP")
        digest = content_hash(payload)
        body = json.dumps(payload, ensure_ascii=False)
        self._execute(
            "UPDATE contributions SET status = ?, title = ?, payload = ?, content_hash = ? "
            "WHERE address = ?",
            (status, title, body, digest, address),
        )
        stored = self.get(address)
        if stored is None:
            raise RuntimeError("contribution update failed")
        return stored

    def latest_event_id(self) -> int:
        row = self._fetchone("SELECT COALESCE(MAX(id), 0) AS max_id FROM events", ())
        return int(row["max_id"]) if row else 0

    def _execute(self, sql: str, params: tuple[Any, ...]) -> None:
        with self._lock:
            if self.kind == "postgres":
                assert self._pg is not None
                self._pg.execute(self._pg_sql(sql), params)
                return
            assert self._sqlite_conn is not None
            self._sqlite_conn.execute(sql, params)
            self._sqlite_conn.commit()

    def _fetchone(self, sql: str, params: tuple[Any, ...]) -> dict[str, Any] | None:
        with self._lock:
            if self.kind == "postgres":
                assert self._pg is not None
                row = self._pg.execute(self._pg_sql(sql), params).fetchone()
                return dict(row) if row is not None else None
            assert self._sqlite_conn is not None
            row = self._sqlite_conn.execute(sql, params).fetchone()
            return dict(row) if row is not None else None

    def _fetchall(self, sql: str, params: tuple[Any, ...]) -> list[dict[str, Any]]:
        with self._lock:
            if self.kind == "postgres":
                assert self._pg is not None
                rows = self._pg.execute(self._pg_sql(sql), params).fetchall()
                return [dict(row) for row in rows]
            assert self._sqlite_conn is not None
            return [dict(row) for row in self._sqlite_conn.execute(sql, params).fetchall()]

    def _pg_sql(self, sql: str) -> str:
        return sql.replace("?", "%s")

    def close(self) -> None:
        with self._lock:
            if self._pg is not None:
                self._pg.close()
                self._pg = None
            if self._sqlite_conn is not None:
                self._sqlite_conn.close()
                self._sqlite_conn = None


def _parse_database(database: str) -> tuple[str, str]:
    if database.startswith(("postgres://", "postgresql://")):
        return "postgres", database
    if database.startswith("sqlite://"):
        parsed = urlparse(database)
        path = parsed.path
        if parsed.netloc == ":memory:" or path in {":memory:", "/:memory:"}:
            return "sqlite", ":memory:"
        return "sqlite", path.lstrip("/") or "upi.db"
    return "sqlite", database


def _row_to_contribution(row: dict[str, Any]) -> Contribution:
    payload = row["payload"]
    if isinstance(payload, str):
        payload = json.loads(payload)
    return Contribution(
        address=row["address"],
        record_type=row["record_type"],
        status=row["status"],
        title=row["title"],
        payload=payload,
        content_hash=row["content_hash"],
        created_at=row["created_at"],
    )


def default_sqlite_path() -> Path:
    """Return the default on-disk sqlite file."""
    return Path("upi.db")
