"""Explicit functional annotations; DER maps, not new legal authority."""

TAGS = frozenset("SOURCE INPUT ACCESS BOUNDARY EXCEPTION IDENTITY RESPONSIBILITY REVIEW SANCTION FEEDBACK".split())

# Every source paragraph is assigned explicitly. A changed inventory fails the build.
CHAPTER_TAGS = {
    1: """
1 SOURCE ACCESS BOUNDARY RESPONSIBILITY
2 BOUNDARY
3 INPUT BOUNDARY
4 BOUNDARY IDENTITY
5 BOUNDARY RESPONSIBILITY
6 BOUNDARY RESPONSIBILITY
7 INPUT ACCESS
8 ACCESS BOUNDARY
9 BOUNDARY RESPONSIBILITY REVIEW
10 SOURCE REVIEW
11 EXCEPTION BOUNDARY
12 EXCEPTION BOUNDARY
13 EXCEPTION IDENTITY BOUNDARY
14 EXCEPTION BOUNDARY
""",
    2: """
1 SOURCE ACCESS
2 BOUNDARY EXCEPTION
3 INPUT BOUNDARY
4 INPUT BOUNDARY ACCESS
5 IDENTITY BOUNDARY
6 INPUT ACCESS BOUNDARY
7 EXCEPTION IDENTITY BOUNDARY
8 INPUT IDENTITY BOUNDARY
9 INPUT BOUNDARY
10 INPUT BOUNDARY
11 INPUT IDENTITY BOUNDARY
12 EXCEPTION INPUT BOUNDARY
13 EXCEPTION BOUNDARY
14 EXCEPTION BOUNDARY
15 ACCESS BOUNDARY
16 ACCESS EXCEPTION BOUNDARY
17 INPUT REVIEW RESPONSIBILITY
18 IDENTITY BOUNDARY
19 REVIEW FEEDBACK EXCEPTION
20 BOUNDARY RESPONSIBILITY
21 ACCESS RESPONSIBILITY BOUNDARY
22 ACCESS RESPONSIBILITY BOUNDARY
23 BOUNDARY RESPONSIBILITY
""",
    3: """
1 IDENTITY ACCESS
2 IDENTITY BOUNDARY REVIEW
3 IDENTITY RESPONSIBILITY BOUNDARY
4 IDENTITY EXCEPTION REVIEW
5 IDENTITY BOUNDARY REVIEW
6 BOUNDARY RESPONSIBILITY
7 SANCTION RESPONSIBILITY
8 IDENTITY BOUNDARY
""",
    4: """
1 ACCESS
2 IDENTITY RESPONSIBILITY SOURCE
3 EXCEPTION BOUNDARY
4 SOURCE RESPONSIBILITY REVIEW
5 SANCTION RESPONSIBILITY
6 BOUNDARY FEEDBACK
7 BOUNDARY FEEDBACK
8 BOUNDARY FEEDBACK
9 BOUNDARY FEEDBACK
""",
    5: """
1 IDENTITY RESPONSIBILITY
2 ACCESS IDENTITY
3 IDENTITY BOUNDARY
4 RESPONSIBILITY BOUNDARY
5 INPUT IDENTITY RESPONSIBILITY
6 INPUT RESPONSIBILITY FEEDBACK
7 INPUT IDENTITY RESPONSIBILITY
8 RESPONSIBILITY BOUNDARY
9 IDENTITY RESPONSIBILITY
10 ACCESS BOUNDARY REVIEW
11 BOUNDARY REVIEW
12 BOUNDARY REVIEW FEEDBACK
13 BOUNDARY REVIEW FEEDBACK
14 IDENTITY BOUNDARY
15 INPUT BOUNDARY RESPONSIBILITY
16 SANCTION RESPONSIBILITY
17 SANCTION RESPONSIBILITY
18 SANCTION IDENTITY
19 SANCTION BOUNDARY
""",
    6: """
1 ACCESS
2 EXCEPTION BOUNDARY
3 EXCEPTION BOUNDARY
4 ACCESS BOUNDARY RESPONSIBILITY
5 SANCTION IDENTITY EXCEPTION
6 SANCTION BOUNDARY
""",
    7: """
1 BOUNDARY RESPONSIBILITY
2 BOUNDARY RESPONSIBILITY SANCTION
3 BOUNDARY EXCEPTION RESPONSIBILITY SANCTION
4 BOUNDARY RESPONSIBILITY SANCTION
5 BOUNDARY RESPONSIBILITY SANCTION
6 BOUNDARY RESPONSIBILITY SANCTION
7 BOUNDARY EXCEPTION RESPONSIBILITY SANCTION
8 BOUNDARY RESPONSIBILITY SANCTION
9 BOUNDARY RESPONSIBILITY SANCTION
10 BOUNDARY RESPONSIBILITY SANCTION
11 BOUNDARY RESPONSIBILITY SANCTION
12 BOUNDARY RESPONSIBILITY SANCTION
13 BOUNDARY RESPONSIBILITY SANCTION
14 BOUNDARY RESPONSIBILITY SANCTION
14a BOUNDARY EXCEPTION RESPONSIBILITY SANCTION
15 BOUNDARY EXCEPTION RESPONSIBILITY SANCTION
16 BOUNDARY EXCEPTION RESPONSIBILITY SANCTION
17 BOUNDARY RESPONSIBILITY SANCTION
18 BOUNDARY RESPONSIBILITY SANCTION
19 BOUNDARY RESPONSIBILITY SANCTION
20 BOUNDARY RESPONSIBILITY SANCTION
21 BOUNDARY EXCEPTION
22 INPUT EXCEPTION RESPONSIBILITY SANCTION
23 INPUT EXCEPTION RESPONSIBILITY SANCTION
24 SANCTION FEEDBACK
25 SANCTION FEEDBACK
26 SANCTION BOUNDARY
27 SANCTION FEEDBACK RESPONSIBILITY
28 SANCTION RESPONSIBILITY
29 SANCTION BOUNDARY EXCEPTION
""",
    8: """
1 IDENTITY RESPONSIBILITY
2 RESPONSIBILITY EXCEPTION
3 IDENTITY RESPONSIBILITY
4 IDENTITY RESPONSIBILITY
5 IDENTITY RESPONSIBILITY
6 IDENTITY RESPONSIBILITY EXCEPTION
7 IDENTITY RESPONSIBILITY EXCEPTION
8 IDENTITY RESPONSIBILITY
9 IDENTITY RESPONSIBILITY
10 IDENTITY RESPONSIBILITY
11 RESPONSIBILITY EXCEPTION
12 RESPONSIBILITY EXCEPTION
13 RESPONSIBILITY REVIEW BOUNDARY
14 RESPONSIBILITY BOUNDARY
""",
    9: """
1 REVIEW RESPONSIBILITY
2 REVIEW RESPONSIBILITY BOUNDARY
3 REVIEW RESPONSIBILITY EXCEPTION
4 INPUT REVIEW BOUNDARY
5 BOUNDARY REVIEW
6 INPUT BOUNDARY
7 INPUT REVIEW
8 REVIEW SANCTION EXCEPTION
9 REVIEW SANCTION EXCEPTION
10 SANCTION RESPONSIBILITY
""",
    10: """
1 SANCTION BOUNDARY
2 REVIEW RESPONSIBILITY BOUNDARY
3 REVIEW FEEDBACK
4 BOUNDARY REVIEW FEEDBACK
5 REVIEW SANCTION
6 REVIEW FEEDBACK
7 BOUNDARY IDENTITY
8 RESPONSIBILITY SANCTION
9 BOUNDARY SANCTION
10 SOURCE ACCESS RESPONSIBILITY
11 FEEDBACK RESPONSIBILITY
12 INPUT REVIEW BOUNDARY
13 EXCEPTION BOUNDARY REVIEW
14 EXCEPTION BOUNDARY RESPONSIBILITY
15 REVIEW FEEDBACK RESPONSIBILITY
""",
    11: """
1 RESPONSIBILITY BOUNDARY
2 RESPONSIBILITY IDENTITY
3 RESPONSIBILITY EXCEPTION
4 RESPONSIBILITY IDENTITY
5 RESPONSIBILITY
6 RESPONSIBILITY EXCEPTION BOUNDARY
""",
    12: """
1 BOUNDARY REVIEW
2 IDENTITY REVIEW
3 REVIEW BOUNDARY
4 REVIEW BOUNDARY
5 REVIEW BOUNDARY
6 REVIEW BOUNDARY FEEDBACK
7 IDENTITY REVIEW
8 IDENTITY REVIEW BOUNDARY
9 IDENTITY REVIEW
10 IDENTITY BOUNDARY
11 IDENTITY REVIEW FEEDBACK
12 IDENTITY REVIEW FEEDBACK
13 IDENTITY REVIEW FEEDBACK
14 IDENTITY SOURCE
15 IDENTITY BOUNDARY
16 IDENTITY REVIEW BOUNDARY
17 IDENTITY REVIEW
18 IDENTITY RESPONSIBILITY EXCEPTION
19 REVIEW BOUNDARY
20 REVIEW RESPONSIBILITY
21 REVIEW BOUNDARY
22 REVIEW BOUNDARY
23 EXCEPTION REVIEW BOUNDARY
""",
    13: """
1 BOUNDARY EXCEPTION
2 INPUT BOUNDARY
3 BOUNDARY RESPONSIBILITY
4 ACCESS EXCEPTION BOUNDARY
5 IDENTITY RESPONSIBILITY
6 SOURCE RESPONSIBILITY
7 INPUT ACCESS EXCEPTION
8 INPUT ACCESS BOUNDARY
9 IDENTITY EXCEPTION BOUNDARY
10 REVIEW RESPONSIBILITY BOUNDARY
""",
    14: """
1 REVIEW FEEDBACK
2 REVIEW IDENTITY FEEDBACK
3 REVIEW BOUNDARY
4 REVIEW BOUNDARY EXCEPTION
5 IDENTITY EXCEPTION BOUNDARY
6 BOUNDARY EXCEPTION
""",
}


def provision_tags() -> dict[str, list[str]]:
    result = {}
    for chapter, lines in CHAPTER_TAGS.items():
        for line in lines.strip().splitlines():
            section, *tags = line.split()
            if not tags or not set(tags) <= TAGS:
                raise ValueError("unknown or empty functional tags")
            result[f"TF {chapter}:{section}"] = tags
    return result
